name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y sqlite3 libsqlite3-dev python3 build-essential
    
    - name: Install dependencies
      run: |
        npm install -g node-gyp
        npm install
        
    - name: List installed packages
      run: npm list
        
    - name: Check directory structure
      run: |
        pwd
        ls -la
        
    - name: Check TypeScript compilation
      run: |
        echo "Running TypeScript compilation check..."
        npx tsc --noEmit --pretty
      
    - name: Run tests with debug output
      run: |
        echo "Setting up test environment..."
        mkdir -p test-workspace
        chmod 777 test-workspace
        echo "Running tests with debug output..."
        NODE_ENV=test DEBUG=* npm test -- --verbose
      env:
        NODE_ENV: test
        DEBUG: "*"
